management:
  endpoints:
    web:
      base-path: /rest/actuator
      exposure:
        include: '*'

springdoc:
  api-docs:
    version: openapi_3_1
  swagger-ui:
    display-request-duration: true
    groups-order: DESC
    operationsSorter: method
    disable-swagger-default-url: true
    use-root-path: true
  show-actuator: true
  cache:
    disabled: true
server:
#  port: 8081
  forward-headers-strategy: framework
