CREATE TABLE IF NOT EXISTS STORE(
    id INT NOT NULL IDENTITY,
    brand VARCHAR(20) NOT NULL,
    location VARCHAR(100) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS PRODUCT (
    id INT NOT NULL IDENTITY,
    name VARCHAR(50) NOT NULL,
    color VARCHAR(20) NOT NULL,
    description VARCHAR(200) NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS STOCK(
    quantity INT NOT NULL,
    productId INT NOT NULL,
    storeId INT NOT NULL,
    FOREIGN KEY (productId) REFERENCES PRODUCT(id),
    FOREIGN KEY (storeId) REFERENCES STORE(id)
);

CREATE TABLE IF NOT EXISTS RESERVATIONS(
    id INT NOT NULL IDENTITY,
    expirationDate DATETIME NOT NULL,
    ipaddress VARCHAR(128) NOT NULL,
    productId INT NOT NULL,
    quantity INT NOT NULL,
    storeId INT NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS ORDERS(
     id INT NOT NULL IDENTITY,
     ipaddress VARCHAR(128) NOT NULL,
     productId INT NOT NULL,
     quantity INT NOT NULL,
     storeId INT NOT NULL,
     PRIMARY KEY (id)
)


